### ISSUE TITLE
Trigger is not working while i generate logic app for blob modification by arm

### ISSUE THREAD

**Issue by ashishm-sdei** [MarczakIO/azure4everyone-samples#1]
Hello MarczaklO,
My trigger is not working as i give input parameter in my logic app if i do any change in my blob container then my trigger is not work if i again select the folder name from gui then it start work for trigger. I am using the same code which you share.
Actually i have to create multiple logic app for blob modification your code is work only for demo one not for other container please help me to sort out.
Thanks and Regards
Ashish

**Comment by MarczakIO** [comment]
Sample is working correctly. ARM has hardcoded /demo container in the path. Feel free to parametrize this if you want. 

Since this is not an issue with the sample I'm closing this.
