### ISSUE TITLE
What is the .net core environment ? 

### ISSUE THREAD

**Issue by Yimin-Yuan** [MarczakIO/azure4everyone-samples#2]
Got the error when run the app System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

**Comment by MarczakIO** [comment]
All samples are running in .NET core. 

Please make sure to watch episode related to attached sample if you want to learn how to use it.

Since this is not an issue with the sample so I'm closing this.
