### ISSUE TITLE
EventHubs Sample -- Receive

### ISSUE THREAD

**Issue by zeesyed** [MarczakIO/azure4everyone-samples#4]
[Hi](url) Marc
In your event hubs sample under the 02-ReceiveEvents and the portal does show in the graphs that there are message being received; but when querying the messages with the below query 
```
SELECT
    *
INTO
    [OutputAlias]
FROM
    [eh01]
```
Where eh01 is my event hub name I see no results. 
This is the error the portal throws: 
`No data was found for preview from 'eh01'. Make sure the input has recently received data and the correct format of those events has been selected.`
I tried enabling capture ,still the same. 
![Screen Shot 2021-06-17 at 6 14 44 PM](https://user-images.githubusercontent.com/6577132/122483361-02917d80-cf98-11eb-8cea-4ab48105ff16.png)
![Screen Shot 2021-06-17 at 6 16 23 PM](https://user-images.githubusercontent.com/6577132/122483426-26ed5a00-cf98-11eb-8808-36fcd0ffe08b.png)
How can I preview the event data in portal to make sure events are actually being received?

**Comment by MarczakIO** [comment]
Hello,

This isn't the issue with the code but something with your configuration on your end. Event hubs must receive data in the 'X' last minutes and you click refresh and it should appear. If it doesn't then there is an issue elsewhere.

Closing this as it's not a code related issue.

Feel free to ask question on YT comment section if you are having non-code related queries.

**Comment by zeesyed** [comment]
Sounds good, thank you for the response.
